# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tmcmcUpdate <- function(x, b, eps, f) {
    .Call('tmcmcR2_tmcmcUpdate', PACKAGE = 'tmcmcR2', x, b, eps, f)
}

rwmhUpdate <- function(x, eps, f) {
    .Call('tmcmcR2_rwmhUpdate', PACKAGE = 'tmcmcR2', x, eps, f)
}

